name: pusht_image_three_goals

image_shape: &image_shape [3, 96, 96]
shape_meta: &shape_meta
  obs:
    image:
      shape: *image_shape
      type: rgb
    agent_pos:
      shape: [2]
      type: low_dim
  action:
    shape: [2]

env_runner:
  _target_: memory_diffusion_policy.env_runner.pusht_image_three_goals_runner.PushTImageThreeGoalsRunner
  n_train: 6
  n_train_vis: 6
  train_start_seed: 0
  n_test: 50
  n_test_vis: 50
  legacy_test: True
  test_start_seed: 100000
  max_steps: 900
  n_obs_steps: ${n_obs_steps}
  n_action_steps: ${n_action_steps}
  fps: 10
  past_action: ${past_action_visible}
  n_envs: ${oc.select:rollout_n_envs,null}
  rollout_mode: ${oc.select:rollout_mode,wandb}

dataset:
  _target_: memory_diffusion_policy.dataset.pusht_three_goals_image_dataset.PushTThreeGoalsImageDataset
  zarr_path: data/pusht_three_goals_demo_vision_320.zarr
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1'}
  pad_after: ${eval:'${n_action_steps}-1'}
  seed: 42
  val_ratio: 0.02
  max_train_episodes: null
