name: pusht_two_goals_lowdim

obs_dim: 20  # 9*2 current keypoints + 2 agent_pos + 9*2 goal_1_keypoints + 9*2 goal_2_keypoints = 18 + 2 + 18 + 18 = 56
action_dim: 2
keypoint_dim: 2

env_runner:
  _target_: memory_diffusion_policy.env_runner.pusht_keypoints_two_goals_runner.PushTKeypointsTwoGoalsRunner
  keypoint_visible_rate: ${keypoint_visible_rate}
  n_train: 6
  n_train_vis: 2
  train_start_seed: 0
  n_test: 50
  n_test_vis: 50
  legacy_test: True
  test_start_seed: 100000
  max_steps: 500  # Increased to allow visiting both goals
  n_obs_steps: ${n_obs_steps}
  n_action_steps: ${n_action_steps}
  n_latency_steps: ${n_latency_steps}
  fps: 10
  agent_keypoints: False
  past_action: ${past_action_visible}
  n_envs: null
  goal_pose_1: [200, 256, 0.785398]  # [x, y, theta] where theta = pi/4
  goal_pose_2: [312, 256, -0.785398]  # [x, y, theta] where theta = -pi/4

dataset:
  _target_: memory_diffusion_policy.dataset.pusht_dataset.PushTLowdimDataset #memory_diffusion_policy.dataset.pusht_two_goals_dataset.PushTTwoGoalsLowdimDataset
  zarr_path: data/pusht_fixed_two_goals_demo.zarr
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1+${n_latency_steps}'}
  pad_after: ${eval:'${n_action_steps}-1'}
  seed: 42
  val_ratio: 0.02
  max_train_episodes: null
